app/models.py
from sqlalchemy.orm import backref
from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from . import login_manager
from flask_login import UserMixin
from datetime import datetime


class Pitch(db.Model):

    __tablename__ = 'pitches'
    id = db.Column(db.Integer, primary_key = True)
    pitch = db.Column(db.String(400))
    name = db.Column(db.String(20))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    likes = db.relationship('Likes', backref = 'likes', lazy = 'dynamic')
    dislikes = db.relationship('Dislikes', backref = 'dislikes', lazy = 'dynamic')
    
    def __repr__(self):
        return '<User %r>' % self.pitch



class User(UserMixin,db.Model):

    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(50))
    email = db.Column(db.String(255))
    password_hash = db.Column(db.String(128))
    name = db.Column(db.String(20))
    bio = db.Column(db.Text())
    member_since = db.Column(db.DateTime, default=datetime.utcnow)
    pitches = db.relationship('Pitch', backref='author', lazy = 'dynamic')
    likes = db.relationship('Likes', backref = 'user', lazy = 'dynamic')
    dislikes = db.relationship('Dislikes', backref = 'dislike', lazy = 'dynamic')

    

    @property
    def password(self):
        raise AttributeError('password is not a readable input')
    
    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    
    def __repr__(self):
        return '<User %r>' % self.username


class Likes(db.Model):
    id = db.Column(db.Integer,primary_key = True)
    upvote = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_likes(cls,id):
        upvotes = Dislikes.query.filter_by(pitch_id =id).all()
        return upvotes

class Dislikes(db.Model):
    id = db.Column(db.Integer,primary_key = True)
    downvote = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_dislikes(cls,id):
        downvotes = Dislikes.query.filter_by(pitch_id =id).all()
        return downvotes




@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired



class PitchForm(FlaskForm):
    pitch = TextAreaField('Enter your Pitch')
    name = StringField('Enter your name', validators=[DataRequired()])
    submit = SubmitField('Pitch', validators=[DataRequired()])

class EditProfile(FlaskForm):
    name = StringField('Enter your name')
    about_me = TextAreaField('Add bio')
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_bootstrap import Bootstrap
from flask_login import LoginManager, login_manager
from flask_mail import Mail

mail = Mail()
db = SQLAlchemy()
bootstrap = Bootstrap()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):

    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    #registering Blueprints
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    #initializing flask extension
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import forms, views

app/main/views.py
from flask_login import login_required, current_user
from . import main
from flask import render_template, url_for,redirect, flash
from .forms import PitchForm, EditProfile
from ..models import Likes, Pitch, User, Dislikes
from .. import db

@main.route('/')
def index():
  return render_template('index.html')

@main.route('/pitches',methods=['GET', 'POST'])
def pitches():

  # pitches = [
  #   {
  #     "pitch": "I recently launched a website for people who like to work on classic cars.      The website has articles and videos with tutorials on how to work on cars",
  #     "name" : "John Doe"

  #   },
  #   {
  #     "pitch" : "I am in the planning stages of a mobile app company in New York. The company will create mobile apps which will help people write business plans on their mobile devices.",
  #     "name" : "Mchimba kisima"
  #   }

  # ]
  pitch_form = PitchForm()
  
  if pitch_form.validate_on_submit():
      pitch = Pitch(pitch =pitch_form.pitch.data, name = pitch_form.name.data)
      db.session.add(pitch)
      db.session.commit()
      return redirect(url_for('.pitches'))
  posts = Pitch.query.all()
  return render_template('pitches.html', posts =posts , pitches = pitches, pitch_form = pitch_form)

  
@main.route('/user/<username>')
def profile(username):
    user = User.query.filter_by(username=username).first()
    posts = user.pitches.all()    
    return render_template('profile.html', user=user, pitches=posts)

@main.route('/like/<int:id>',methods = ['POST','GET'])
@login_required
def like(id):
    get_pitches = Likes.get_likes(id)
    valid_string = f'{current_user.id}:{id}'
    for pitch in get_pitches:
        to_str = f'{pitch}'
        print(valid_string+" "+to_str)
        if valid_string == to_str:
            return redirect(url_for('main.pitches',id=id))
        else:
            continue
    new_vote = Likes(user=current_user, pitch_id=id)
    new_vote.save()
    return redirect(url_for('main.pitches',id=id))


@main.route('/dislike/<int:id>',methods = ['POST','GET'])
@login_required
def dislike(id):
    get_pitches = Dislikes.get_dislikes(id)
    valid_string = f'{current_user.id}:{id}'
    for pitch in get_pitches:
        to_str = f'{pitch}'
        print(valid_string+" "+to_str)
        if valid_string == to_str:
            return redirect(url_for('main.pitches',id=id))
        else:
            continue
    new_vote = Dislikes(dislike=current_user, pitch_id=id)
    new_vote.save()
    return redirect(url_for('main.pitches',id=id))





@main.route('/edit-profile', methods = ['GET','POST'])
@login_required
def edit():
    form = EditProfile()
    if form.validate_on_submit():
      current_user.username = form.name.data
      current_user.bio = form.about_me.data
      db.session.add(current_user._get_current_object())
      db.session.commit()
      flash('Your profile has been updated.')
      return redirect(url_for('.profile', username=current_user.username))
    form.name.data = current_user.username
    form.about_me= current_user.bio
    return render_template ('edit-profile.html', form = form)



  

app/templates/edit-profile.html
{% extends 'layout.html' %}
{%block css%}
<link rel="stylesheet" href="{{url_for('static', filename = 'css/auth.css')}}">
{% endblock %}

{% import 'bootstrap/wtf.html'as wtf %}

{% block content%}
<div class="back">
  <div class = 'container'>
    <div class="form-container">
      <div class="head">
        <h1>EDIT PROFILE</h1>
      </div>
      <div class="fm-body">
        {{wtf.quick_form(form)}}
      </div>
    </div>
  
  </div>
</div>

{% endblock %}

app/templates/edit.html
{% extends 'layout.html' %}

{% import 'bootstrap/wtf.html'as wtf %}

{% block content%}
{{wtf.quick_form(form)}}
{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}

{% block css %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/home.css') }}">
{% endblock%}
{% block title%}
 Homepage
{% endblock %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-5 content">
      <div class = "two"></div>
      <h1>Engage Your Audience in Minutes</h1>
      <p>Powerful platform to pitch yourself in 60 seconds</p>
      </div>
    <div class="col-md-7">
      <img src="{{url_for('static', filename = 'images/hero.png')}}" alt="">
    </div>
  </div>
<div class = "one"></div>
      
<a href="{{url_for('auth.login')}}"><button class = "btn custom"> Add Pitch</button></a>
</div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
    integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
  <!-- favicon  -->
  <link rel="shortcut icon" href="{{url_for('static', filename = 'images/favicon.ico')}}" type="image/x-icon">
  <!-- Google fonts -->

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Text&family=Poppins:wght@100&display=swap"
    rel="stylesheet">

  <!-- css -->

  {% block css%}
  {% endblock %}
    <!-- js -->
 {% block script %}
 {% endblock %}
  
  {% extends 'bootstrap/base.html' %}
  {% block title %}
  <title></title>
  {% endblock %}
</head>

<body>
  {% block navbar %}
  <div class="navbar navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TALKY</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right">
          <li><a href="{{url_for('main.index')}}">Home</a></li>
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('auth.logout')}}"><i class="fas fa-sign-out-alt"></i> Logout</a></li> 
          <li><a href="{{url_for('main.pitches')}}"> <i class="fas fa-comments-dollar"></i>Pitches </a></li>
          <li><a href="{{url_for('main.profile', username=current_user.username)}}"> <i class="fas fa-user-alt"></i> Profile</a></li>

          {% else %}
          <li class=""><a href="{{url_for('auth.login')}}"><i class="fas fa-sign-in-alt"></i> Login</a></li>
          <li><a href="{{url_for('auth.register')}}">SignUp</a></li>
          {% endif %}

          

        </ul>
      </div>
    </div>
  </div>
  {% endblock %}

  {% block content %}
  {% endblock %}

 

 
</body>

</html>

app/templates/pitches.html
{% extends 'layout.html' %}


{% import 'bootstrap/wtf.html' as wtf%}

{%block css%}
<link rel="stylesheet" href="{{url_for('static', filename = 'css/pitch.css')}}">
{% endblock %}
{% block script %}
<script src="{{url_for('static',filename = 'js/app.js')}}"></script>
{% endblock %}
{%block title%}
  pitches
{% endblock %}
{%block content%}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="pitch-head">
        <h1>
          Pitch Yourself Below
        </h1>
        <div class="pitch-content">
          <div>
            {% for post in posts %}
            <h6>{{post.pitch}}</h6>
            <em><p>{{post.name}}</p></em>
            <a href="{{url_for('main.like', id = post.id)}}"><i class=" icon fas fa-thumbs-up"></i></a><span class = "custom"> {{post.likes.count()}} </span></p>
            <a href="{{url_for('main.dislike', id =post.id )}}"><i class="fas fa-thumbs-down"></i></a> <span class = "custom"> {{post.dislikes.count()}}</span></p>
            <hr>
            <a href="">Add comment</a>
            <br>
            <br>
          {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="categories">
        <div class="cat-holder">

          {{wtf.quick_form(pitch_form)}}
        </div>



      </div>
    </div>
  </div>

</div>
{% endblock %}

app/templates/profile.html
{% extends 'layout.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='css/profile.css')}}">
{%  endblock %}
{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
 {{message}}
</div>
{% endfor %}
{% endif%}
{% endwith %}
<div class="container">
  <div class="row ">
    <div class="col-md-7 cont-prof">
      <h1 class = "text-center">My pitches</h1>
      <h4>{{user.pitches}}</h4>
      
    </div>
    <div class="col-md-5">
      <div class = 'image'>
        <img src="{{url_for('static', filename = 'images/profile.jpg')}}" alt="">
      </div>
     <h1>{{user.username}} <i class="fas fa-check-circle"></i>
    </h1>
      <p>{{user.email}}</p>
      <p>{{user.bio}}</p>
      <a href="{{url_for('main.edit')}}"><button class = 'btn'>Edit Profile</button></a>          
    </div>
  </div>
</div>
{% endblock %}

app/templates/register.html
{% extends 'layout.html' %}

{% import 'bootstrap/wtf.html as wtf' %}

<div class = 'container'>
  <div class="form-container">
    <div class="head">
      <h1>REGISTER</h1>
    </div>
    <div class="fm-body">
      {{wtf.quick_form(form)}}
    </div>
  </div>

</div>